version: "3.7"
name: server-dependencies
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda-0: null
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

