// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Event struct {
	ID            string         `json:"ID"`
	Name          string         `json:"name"`
	Version       string         `json:"version"`
	Release       string         `json:"release"`
	PlatformID    string         `json:"platformID"`
	Package       string         `json:"package"`
	Description   string         `json:"description"`
	Payload       string         `json:"payload"`
	EventReceiver *EventReceiver `json:"event_receiver"`
	Success       bool           `json:"success"`
	CreatedAt     *time.Time     `json:"created_at,omitempty"`
	UpdatedAt     *time.Time     `json:"updated_at,omitempty"`
}

type EventInput struct {
	Name            string `json:"name"`
	Version         string `json:"version"`
	Release         string `json:"release"`
	PlatformID      string `json:"platformID"`
	Package         string `json:"package"`
	Description     string `json:"description"`
	Payload         string `json:"payload"`
	EventReceiverID string `json:"event_receiver_id"`
	Success         bool   `json:"success"`
}

type EventReceiver struct {
	ID          string     `json:"ID"`
	Name        string     `json:"name"`
	Type        string     `json:"type"`
	Version     string     `json:"version"`
	Description string     `json:"description"`
	Enabled     bool       `json:"enabled"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

type EventReceiverGroup struct {
	ID             string           `json:"ID"`
	Name           string           `json:"name"`
	Type           string           `json:"type"`
	Version        string           `json:"version"`
	Description    string           `json:"description"`
	Enabled        bool             `json:"enabled"`
	EventReceivers []*EventReceiver `json:"event_receivers"`
	CreatedAt      *time.Time       `json:"created_at,omitempty"`
	UpdatedAt      *time.Time       `json:"updated_at,omitempty"`
}

type EventReceiverGroupInput struct {
	Name             string   `json:"name"`
	Type             string   `json:"type"`
	Version          string   `json:"version"`
	Description      string   `json:"description"`
	Enabled          bool     `json:"enabled"`
	EventReceiverIds []string `json:"event_receiver_ids"`
}

type EventReceiverInput struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
}
