version: '3.8'

networks:
  epr-network:
    driver: bridge

volumes:
  postgres-data: null
  redpanda-data: null

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      EPR_BROKERS: redpanda:19092
      EPR_DB: postgres://postgres:5432
    volumes:
      - ..:/workspaces:cached
    tty: true
    ports:
      - 8042:8042
    networks:
      - epr-network
