version: '3.8'

services:
  epr-development:
    extends:
      file: ./docker-compose.yaml
      service: epr-server
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    tty: true
